### ISSUE TITLE
[Feature] Use the new `pkgver()` function in `-git` pacscripts.

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall-programs#12]
**Is your feature request related to a problem? Please describe.**
From Pacstal 1.3 "Amaranth" a new `pkgver()` function was introduced (see [here](https://github.com/pacstall/pacstall/releases) for info), so can we add that function to the `-git` pacscripts to enable auto updates?

**Describe the solution you'd like**
Use the `pkgver()` function to enable auto updates in `-git` pacscripts

**Describe alternatives you've considered**
None

**Additional context**
The pacscripts refered in this context are of these teams:
@pacstall/bashtop-git 
@pacstall/blang-git 
@pacstall/bpytop-git 
@pacstall/lemonbar-xft-git 
@pacstall/notion-git 
~@pacstall/pipewire-git~
@pacstall/st-distrotube 
~@pacstall/st-lukesmith~
@pacstall/tuner-git

**Comment by wizard-28** [comment]
@pacstall/emacs

**Comment by erikLundstedt** [comment]
my pacget installscript shoud maybe be renamed with -git(there is no other version) and i should probably implement that function


I will work on that today
