### ISSUE TITLE
PacReq: `firefox`

### ISSUE THREAD

**Issue by ghost** [pacstall/pacstall-programs#1285]
### Types

-bin (Binary release of the package)

### URL

https://download-installer.cdn.mozilla.net/pub/firefox/releases/101.0.1/linux-x86_64/en-US/firefox-101.0.1.tar.bz2

### Building guide

https://support.mozilla.org/en-US/kb/install-firefox-linux

### Additional context

N/A

**Comment by brainchild0** [comment]
Linux Mint publishes builds of Firefox that I expect are fully compatible with Ubuntu, but they are always based on LTS.

**Comment by brainchild0** [comment]
Also available from [PPA `mozillateam/ppa`](https://launchpad.net/~mozillateam/+archive/ubuntu/ppa).

**Comment by Diegiwg** [comment]
Firefox is already available, it should lock this request.
