### ISSUE TITLE
Bug: Emacs package missing dependencies

### ISSUE THREAD

**Issue by JonBoyleCoding** [pacstall/pacstall-programs#1303]
The emacs package appears to be missing some dependencies needed to make it compile (at least on Ubuntu 20.04). The current AUR package has a number of other dependencies: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emacs28-git

The following are what I needed to get this compiled (or at least to start compiling - will update if anything more is needed)
- libgtk-3-dev
- libxpm-dev
- libgif-dev

**Comment by JonBoyleCoding** [comment]
Has this been looked at at all?

**Comment by Henryws** [comment]
> Has this been looked at at all?

Yes sorry, forgot about this.
