### ISSUE TITLE
PacReq: gtkmm4 and its libraries for developing

### ISSUE THREAD

**Issue by Master811129** [pacstall/pacstall-programs#1498]
### Types

nosuffix? (maybe `-dev` i guess)

### URL

[Official website](http://www.gtkmm.org/en/)
[Gitlab Source](https://gitlab.gnome.org/GNOME/gtkmm)

### Building guide

[Building guide](https://gitlab.gnome.org/GNOME/gtkmm/-/blob/master/README)

### Additional context

Please make it out-of-the box, just like the arch one. install and develop. i really need it in ubuntu. thank you for making this project. Thank you.

**Comment by Master811129** [comment]
@Mar0xy thank you for making it. What you did was a big help for me. I have some questions.
- can i now use it?
- can i use it in ubuntu-based distros like Linux Mint or Zorin?

**Comment by Henryws** [comment]
Yes, you can now use it, and it will work on Ubuntu based distros

**Comment by Master811129** [comment]
@Mar0xy @Henryws this package does not work with ubuntu 20.04 (Zorin OS 16.1) because there is no gtk 4 :(

```
The following packages have unmet dependencies:
 gtkmm4 : Depends: libgtk-4-1 but it is not installable
[!] ERROR: Failed to install dependencies
dpkg: warning: ignoring request to remove gtkmm4 which isn't installed
[+] INFO: Cleaning up
[!] ERROR: Failed to install gtkmm4

```

**Comment by Mar0xy** [comment]
that is too old of an version you need newer version since gtk4 is officially supported from 21.10 and up

**Comment by Master811129** [comment]
can you make gtk4 possible?
the reason i wanna do this is to provide an AppImage for my opensource software. according to the developer of AppImage you should use ubuntu trusty to maximize the compatibility.  I think i have to drop the support for appimage altogether which is a shame tbh.

**Comment by Mar0xy** [comment]
sadly no cause making GTK4 possible would mean porting about 10-20 libraries and also hoping they work with all current libs on old ubuntu

**Comment by Master811129** [comment]
You're right, totally understandable.
