### ISSUE TITLE
Outdated package: vscode-deb

### ISSUE THREAD

**Issue by mrquantumoff** [pacstall/pacstall-programs#1510]
Latest link for the deb file: https://az764295.vo.msecnd.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/code_1.70.2-1660629410_amd64.deb
Latest version as of august 26: 1.70.2

**Comment by 0x262D** [comment]
As I understand it, the problem is that the site generates one-time links for each individual download.
So to solve the problem, you need to understand how links are generated.
![1](https://user-images.githubusercontent.com/112124572/187068868-d2b46bbf-a312-4318-91ae-8eae0f7acd85.png)
