### ISSUE TITLE
PacReq: <Amberol> for 20.04

### ISSUE THREAD

**Issue by FreeFight3r** [pacstall/pacstall-programs#1520]
### Types

nosuffix (Compiled off of the released source code)

### URL

https://gitlab.gnome.org/World/amberol

### Building guide

[Amberol](https://gitlab.gnome.org/World/amberol/-/blob/main/CONTRIBUTING.md#your-first-contribution)
[GTK4 (official)](https://docs.gtk.org/gtk4/building.html)
[GTK4 (a bit more detailed)](https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/sec2.md)

### Additional context

please make this available for Ubuntu 20.04 i don't like snaps.

**Comment by FreeFight3r** [comment]
I saw the pacscript i don't think it is doable on 20.04

**Comment by Henryws** [comment]
It does work on 20.04

**Comment by FreeFight3r** [comment]
@Henryws  `libgtk-4-dev` is not in focal's repos

```
zorin@zorin:~$ sudo apt search libgtk-4-dev
Sorting... Done
Full Text Search... Done
```
so I don't think the build script can do anything about it... You need to compile gtk4.

**Comment by Elsie19** [comment]
Appears to be in latest apt repos.
