### ISSUE TITLE
PacReq: intel-undervolt

### ISSUE THREAD

**Issue by redzrush101** [pacstall/pacstall-programs#1612]
### Types

nosuffix (Compiled off of the released source code)

### URL

https://github.com/kitsunyan/intel-undervolt/archive/refs/tags/1.7.tar.gz

### Building guide

https://github.com/kitsunyan/intel-undervolt#building-and-installing

### Additional context

build-essentials and git are dependencies.

**Comment by Henryws** [comment]
I'll work on this.
