### ISSUE TITLE
PacReq: Ungoogled Chromium

### ISSUE THREAD

**Issue by brainchild0** [pacstall/pacstall-programs#1726]
### Types

-deb (Debian achieve release of the package)

### URL

https://github.com/ungoogled-software/ungoogled-chromium

### Building guide

https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/building.md

### Additional context

Debian package from custom repository had worked on versions of LTS Ubuntu that are now outdated, but the repository no longer is maintained with a working key or populated with current builds.

**Comment by jimed-rand** [comment]
I am sorry to reply it this time on 2024 while you requested 2 years ago.

I could add it the `deb` version, but only this version (`100.0.4896.127-1`) could be added for that. Is that okay to add it this version ?

**Comment by jimed-rand** [comment]
https://github.com/berkley4/ungoogled-chromium-debian/releases

Now I got the newest sources for `ungoogled-chromium-deb`, I'll use this as new base.

**Comment by jimed-rand** [comment]
Now commit #6453 has been live on official repo @brainchild0 
You can close this issue as complete.
