### ISSUE TITLE
PacReq: noisetorch

### ISSUE THREAD

**Issue by Sophed** [pacstall/pacstall-programs#1785]
### Types

-bin (Binary release of the package)

### URL

https://github.com/noisetorch/NoiseTorch

### Building guide

https://github.com/noisetorch/NoiseTorch#download--install

**Comment by Mar0xy** [comment]
Already exists under https://github.com/pacstall/pacstall-programs/blob/master/packages/noisetorch-bin/noisetorch-bin.pacscript
