### ISSUE TITLE
PacReq: toolbox

### ISSUE THREAD

**Issue by brainchild0** [pacstall/pacstall-programs#1791]
### Types

nosuffix (Compiled off of the released source code)

### URL

https://github.com/containers/toolbox

### Building guide

- Go implementation
- Meson & ninja build systems

See [Dependencies and Building](https://containertoolbx.org/install/)

### Additional context

Developed by RedHat for Fedora, but potentially very useful to Ubuntu users for isolating development environments.

**Comment by Mar0xy** [comment]
Distrobox also already achieves the same thing as toolbox with a few more features and is already on here.
