### ISSUE TITLE
neovim recursively installs

### ISSUE THREAD

**Issue by Henryws** [pacstall/pacstall-programs#214]
**Describe the bug**
When installing neovim, the contents of `/usr/src/pacstall/neovim` is `usr/src/pacstall/neovim`

**To Reproduce**
Install neovim

**Expected behavior**
For the contents of `/usr/src/pacstall/neovim` to contain something like `bin/nvim`

**Comment by wizard-28** [comment]
Most probably this line is the issue
https://github.com/pacstall/pacstall-programs/blob/cf92d3d3c5098f1cd8cfeae092fc078b1028ecfc/packages/neovim/neovim.pacscript#L17

The prefix should be the "prefix" not the directory location (which is handled by `DESTDIR`)
Try refactoring the prefix to `/usr` or `/usr/local` (The "prefix" of the install), or just leave it blank for the default `/usr/local`

**Comment by wizard-28** [comment]
As a side note, please add the `maintainer` field to this script, it's missing one.

**Comment by wizard-28** [comment]
Closing this, as it's probably fixed in https://github.com/pacstall/pacstall-programs/commit/d126bb68764af68e3de3de9a6bf925a0eb0672c6
