### ISSUE TITLE
PacReq: Opera Web Browser

### ISSUE THREAD

**Issue by RDKRACZ** [pacstall/pacstall-programs#233]
From AUR: A fast and secure web browser and Internet suite.

URL:  https://www.opera.com
Building Guide: Not open-source.

**Comment by RDKRACZ** [comment]
I'm not sure if I have done it right. Are there any apps that should not be requested? I also wanted to request https://github.com/shssoichiro/oxipng and https://github.com/JayXon/Leanify but I don't want to spam or sth. Should I open separate issues?

**Comment by Henryws** [comment]
I would open them in separate issues. As for the apps that shouldn't be requested, no, there are none, you can request whatever you want (as long as it's not malware)

**Comment by wizard-28** [comment]
@RDKRACZ I volunteer to work on `opera-deb`

**Comment by wizard-28** [comment]
@RDKRACZ check #239, see if the script works.
