### ISSUE TITLE
PacReq: telegram-desktop

### ISSUE THREAD

**Issue by RDKRACZ** [pacstall/pacstall-programs#234]
Telegram messenger desktop client
URL:  https://github.com/telegramdesktop/tdesktop; https://desktop.telegram.org/
Building Guide:  https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md

Also requesting because the auto-updater is broken, at least for me.

**Comment by wizard-28** [comment]
@RDKRACZ Telegram apparently ship [Linux 64-bit binaries](https://github.com/telegramdesktop/tdesktop/releases/download/v3.0.1/tsetup.3.0.1.tar.xz), so do you want a `-bin` pacscript or a `no suffix` one (building)?

*PS: If you are unsure about the suffix, you can read [my response on reddit](https://www.reddit.com/r/pacstall/comments/pfmahd/download_binaries_instead_of_building_from_the/hb5fxqy?utm_source=share&utm_medium=web2x&context=3).*

**Comment by RDKRACZ** [comment]
The binary package is already built so if it doesn't have any disadvantages (I know sometimes -bin is out-of-date like [this one](https://github.com/JayXon/Leanify/releases), yeah only 6 years, there are commits from 2021) then it should be better.

**Comment by wizard-28** [comment]
Okay, then I volunteer to make this script
