### ISSUE TITLE
PacReq: Microsoft Edge Beta and Dev.

### ISSUE THREAD

**Issue by RDKRACZ** [pacstall/pacstall-programs#235]
Web browser created and developed by Microsoft.
URL:  https://www.microsoftedgeinsider.com/en-us/download?platform=linux-deb
Building Guide:  Closed-source.

**Comment by NarutoXY** [comment]
Partially fixed with #254

**Comment by wizard-28** [comment]
@RDKRACZ as a side note, make separate issues for **each** request you make. It's easier for us to manage and process your requests then.

**Comment by NarutoXY** [comment]
Fixed completely by #254 and #255
