### ISSUE TITLE
PacReq: Caprine

### ISSUE THREAD

**Issue by RDKRACZ** [pacstall/pacstall-programs#240]
Facebook Messenger unofficial Linux client
URL:  https://github.com/sindresorhus/caprine; https://sindresorhus.com/caprine/
Building Guide:  https://github.com/sindresorhus/caprine#build

**Comment by wizard-28** [comment]
With what suffix? They provide `.deb`, `.AppImage` or we can build it locally.

**Comment by RDKRACZ** [comment]
Deb would be the best imo.

**Comment by wizard-28** [comment]
I volunteer then
