### ISSUE TITLE
Include pacstall-programs in Repology

### ISSUE THREAD

**Issue by AndersonTorres** [pacstall/pacstall-programs#257]
**Is your feature request related to a problem? Please describe.**

Repology is a database service which tracks and compares packages in a plethora of repositories, from Linux distros to specialized repos like Chocolatey and crates.io.

**Describe the solution you'd like**

Prepare pacstall-programs in order to be suitable for inclusion in repology database.

**Describe alternatives you've considered**

No alternatives were considered. Repology is a de facto standard solution on its niche.

**Additional context**

- Repology Documentation: http://repology.org/docs
- Guidelines for inclusion: https://repology.org/addrepo

**Comment by wizard-28** [comment]
Yeah, so how exactly would we do this currently?

**Comment by wizard-28** [comment]
> I would suggest something like a batch script that walks through the repository, extracts the relevant information and generates a JSON listing from that extracted info. It would be something like the packagelist on steroids!

we created a prototype python script for this in our discord. It's not done yet though.

**Comment by AndersonTorres** [comment]
Amdmi3 said [any HTTP link can be used](https://github.com/repology/repology-updater/issues/1212#issuecomment-1007274377).

On the other hand, he suggested not to use the master branch on github, because it would pollute the commit logs.

In this scenario, I suggest to upload this JSON file on some dedicated page on https://pacstall.dev/ ; something like https://pacstall.dev/packagelist.json.

(As a side project, it would be cool to add a fancy search engine...)

**Comment by Henryws** [comment]
https://repology.org/repository/pacstall
🎉
