### ISSUE TITLE
PacReq: latte-dock-git

### ISSUE THREAD

**Issue by ty1118** [pacstall/pacstall-programs#260]
Replacement dock for Plasma desktops, providing an elegant and intuitive experience for your tasks and plasmoids

Resources

URL:https://github.com/KDE/latte-dock/archive/refs/heads/master.zip
Building Guide: https://github.com/KDE/latte-dock/blob/master/INSTALLATION.md

Requested By: Tyler Johnson

**Comment by wizard-28** [comment]
I volunteer.

**Comment by wizard-28** [comment]
@ty1118 Can you test the script?

1. Open the linked PR
2. Download / Copy the `.pacscript` from `Files` tab.
3. Run `pacstall -P -Il latte-dock-git`

For the first run **don't** select `Y` on optional dependencies (X11 support). If it finishes successfully then uninstall it. Then again install it, this time **do** select `Y` on optional dependencies.

**Comment by ty1118** [comment]
ok thank you

**Comment by wizard-28** [comment]
@ty1118 don't forget to keep the installation logs in both cases.

Paste them in the PR after installation.

**Comment by ty1118** [comment]
stow: ERROR: The stow directory usr/src/pacstall does not contain package latte-dock-git

**Comment by ty1118** [comment]
how do i fix this

**Comment by wizard-28** [comment]
Firstly, converse about this in the linked PR #261 

Secondly, it means that the `install` part of the script didn't succeed (probably because `build` didn't succeed either). Can you post the whole build log in the PR?

**Comment by ty1118** [comment]
where do i find the logs? (I'm a total newbie, sorry)

**Comment by wizard-28** [comment]
Just copy-paste what was printed on the screen when you ran `pacstall -P -Il latte-dock-git`

**Comment by ty1118** [comment]
OKay, on it.

**Comment by ty1118** [comment]
worked like a charm thank you so much!!!!

**Comment by wizard-28** [comment]
@ty1118 Post the logs in the PR. Also, are you on X11 or Wayland?

**Comment by ty1118** [comment]
x11

**Comment by wizard-28** [comment]
Hmm... Anyways post the logs in the PR.
