### ISSUE TITLE
PacReq: zettlr

### ISSUE THREAD

**Issue by Anifyuli** [pacstall/pacstall-programs#2787]
### Types

-deb (Debian achieve release of the package)

### URL

https://www.zettlr.com/download

### Building guide

https://aur.archlinux.org/packages/zettlr-git

### Additional context

I like this app, and I hope this app can included in Pacstall

**Comment by smokeythemonkey** [comment]
See PR https://github.com/pacstall/pacstall-programs/pull/2860
