### ISSUE TITLE
PacReq: CMake

### ISSUE THREAD

**Issue by ty1118** [pacstall/pacstall-programs#284]
CMake is an open-source, cross-platform family of tools designed to build, test and package software. CMake is used to control the software compilation process using simple platform and compiler independent configuration files, and generate native makefiles and workspaces that can be used in the compiler environment of your choice. 

URL: https://cmake.org/
Build Guide: https://roboticslab-uc3m.github.io/installation-guides/install-cmake.html#install-cmake-319-ubuntu-1804-bionic

Requested By:Tyler Johnson

**Comment by wizard-28** [comment]
Shouldn't this be installable through `pip3`?

```bash
sudo pip3 install --upgrade cmake
```
