### ISSUE TITLE
PacReq: Cantata

### ISSUE THREAD

**Issue by ty1118** [pacstall/pacstall-programs#300]
Cantata is a graphical client for MPD. It contains the following features:

 1. Support for Linux, MacOSX, and Windows.
 2. Multiple MPD collections.
 3. Highly customizable layout.
 4. And More.

URL: https://github.com/CDrummond/cantata
Building Guide: https://github.com/CDrummond/cantata/blob/master/INSTALL

**Comment by wizard-28** [comment]
This will be a very simple script. You can try to add this one yourself @ty1118, otherwise someone else can of course add this.

**Comment by ty1118** [comment]
ok ill give it a shot

**Comment by ty1118** [comment]
I took care of it. It works great for the easy setup.

Below is the script itself.


name="cantata-deb"
pkgname="cantata-deb"
version="2.4.2"
url="https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/cantata-qt/+files/cantata_2.4.2-0build1~ubuntu20.10_amd64.deb"
license="GPL"
depends="mpd media-player-info fonts-font-awesome libcddb2 libebur128-1 libmusicbrainz5cc2v5 libqt5multimedia5"
gives="cantata-deb"
description="Cantata is a graphical client for MPD. It is support for Linux, MacOSX, and Windows, Multiple MPD collections and it has a Highly customizable layout."
hash="9f9a1f674aca7b2313fa9888ac8e488fa6c0bbb6e4339f1a9a882b0687105508"

**Comment by Henryws** [comment]
Um, in order to add this package to pacstall, you need to create a [PR](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by ty1118** [comment]
got it

**Comment by ty1118** [comment]
how do i do that

**Comment by Henryws** [comment]
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by ty1118** [comment]
ive got no idea of what im doing i need some help with the pull request

**Comment by wizard-28** [comment]
I volunteer for this. I'll do it sometime this week.

**Comment by wizard-28** [comment]
@ty1118 what suffix did you want? `-git` or `nosuffix` (Others are not applicable for this program)

**Comment by ty1118** [comment]
-git
