### ISSUE TITLE
PacReq: Grapejuice

### ISSUE THREAD

**Issue by ruzko** [pacstall/pacstall-programs#309]
Grapejuice is a management tool for playing Roblox using Wine.
Roblox is a fun game played by many children, but it doesn't run using only Wine. Grapejuice is currently available in the AUR, and it works well on arch-based distros. Installing applications from source is not every parent or child's cup of tea, therefore it would be good to simplify the installation process by including it in pacstall-programs.

URL: https://gitlab.com/brinkervii/grapejuice
Building Guide: https://gitlab.com/brinkervii/grapejuice/-/wikis/Installing-from-source/Debian-10-and-similar

**Comment by ty1118** [comment]
ill try to do it

**Comment by ty1118** [comment]
the problem with this is that the build guide is different for certain versions of ubuntu. it makes it a tad more difficult to develop rather than using cmake.

**Comment by ruzko** [comment]
Could I offer a bounty to get grapejuice working?

I've been trying for days to get Roblox working on my nephew's laptop running Kubuntu 21.04, but to no avail.
Maybe it would be better to ask upstream for troubleshooting help with my specific issue

**Comment by Henryws** [comment]
I can work on that now

**Comment by Henryws** [comment]
ok, I've finished the script, and I'm making the relevant PR now
