### ISSUE TITLE
PacReq: xmind-deb

### ISSUE THREAD

**Issue by Anifyuli** [pacstall/pacstall-programs#3204]
### Types

-deb (Debian achieve release of the package)

### URL

https://dl3.xmind.net/Xmind-for-Linux-amd64bit-22.11.3656.deb

### Building guide

wget https://dl3.xmind.net/Xmind-for-Linux-amd64bit-22.11.3656.deb
sudo dpkg -i Xmind-for-Linux-amd64bit-22.11.3656.deb

### Additional context

I wish this packages can add to Pacstall quickly

**Comment by Henryws** [comment]
```bash
name="xmind-vana-deb"
gives="xmind-vana"
version="22.11.3656-202301100025"
url="https://dl3.xmind.net/Xmind-for-Linux-amd64bit-${version%-*}.deb"
description="Mind mapping and brainstorming app"
hash="b2cbf5e757e6f51bb45ffbf864250409896b02633f2d0570584aa298677d3c05"
arch=("amd64")
```

Does this look good?

**Comment by Anifyuli** [comment]
It's look good, Mister
