### ISSUE TITLE
PacReq: libnvinfer-bin(-deb)

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall-programs#3309]
### Types

Not sure if -bin or -deb

### URL

https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/libnvinfer-bin_8.6.1.6-1+cuda12.0_amd64.deb

### Building guide

wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
sudo dpkg -i cuda-keyring_1.0-1_all.deb
sudo apt update
sudo apt install libnvinfer-bin

### Additional context

I want to add this library to pacstall to create an alternative obs-backgroundremoval, which would have gpu support
I am not so sure how to package it
Basically, nvidia provides a repository for this
Is it ok to add the repository to sources in the pacscript and then install the package from there?
This package depends on `cuda-toolkit-12-1-config-common cuda-toolkit-12-config-common cuda-toolkit-config-common libcublas-12-1  libcudnn8 libnvinfer-bin libnvinfer-dispatch8 libnvinfer-lean8 libnvinfer-plugin8 libnvinfer-vc-plugin8  libnvinfer8 libnvonnxparsers8 libnvparsers8`, which are also in that repository.
The download is 1,223 MB and installs 3,104 MB, so it’s pretty big, that is why I would like to provide versions with and versions without the gpu support.

Help would be appreciated for this one.

**Comment by Henryws** [comment]
> Is it ok to add the repository to sources in the pacscript and then install the package from there?

No.

**Comment by Zahrun** [comment]
Turns out the CPU only mode got much better and beats the GPU mode on my machine so I’ll skip this. Details at https://github.com/royshil/obs-backgroundremoval/issues/301
