### ISSUE TITLE
PacReq: GOverlay

### ISSUE THREAD

**Issue by intelligentgaming** [pacstall/pacstall-programs#3394]
### Types

-git (Compiled off of the latest commit of the package)

### URL

https://github.com/benjamimgois/goverlay

### Building guide

https://github.com/benjamimgois/goverlay#building

### Additional context

Ubuntu 22.04 based distributions such as Pop OS package an older version of GOverlay that does not work, unless you manually build MangoHUD from scratch.

Plus MangoHUD is already available in the Pacstall repository, so it would make sense to have the GUI tool to manage said tool available as well.

**Comment by Henryws** [comment]
Would it be ok if I made a no-suffix package (not `-git`)? The reason why I'm asking is because there's only 1 new commit since the last release and that's a typo on the readme.

**Comment by intelligentgaming** [comment]
That sounds great to me, let me if you need me to do some testing.
