### ISSUE TITLE
[Help-Wanted] Removescript function not running

### ISSUE THREAD

**Issue by harsh18262** [pacstall/pacstall-programs#359]
Hello,
I have made a script https://pastebin.com/W3cDRZpf for a package,but the removescript function is not executing when uninstalling the package?

Can anyone please check and guide me a little

**Comment by wizard-28** [comment]
Can you provide which version of Pacstall are you using? Also can you upgrade to the develop branch ( if you are already not on it), and try to (un)install this package again?

Here's the command to update to the develop branch:
```
pacstall -U pacstall develop
```

**Comment by harsh18262** [comment]
I am using the stable 1.5.1 Moonlight version. while using the development branch the package is not installing does the development branch need some special permissions to some directory? I am currently using a docker container to test it but i am getting the error of hash mismatch which is not happening with stable branch also with develop branch the i3lock-color(i am the maintainer for that) package is not installing there is some problem while creating the dummy package.

Also is there anyway to get more verbose output from pacstall while installing?

log
https://pastebin.com/vm4nzn08

**Comment by wizard-28** [comment]
> The development branch is near release at the moment, and doesn't require extra file/directory permissions.
The problem you had actually helped me find a bug related to pacdep fails.

I think the `SRCDIR` needs a `chmod`, it's handled by the new installler I think.

**Comment by wizard-28** [comment]
Can you run through the new installer once? The development version needs to be "reinstalled" to work I think.

Run this
```bash
sudo bash -c "$(curl -fsSL https://git.io/Jue3Z)" && pacstall -U pacstall develop
```

To reinstall, and update to the dev branch directly (your installed packages will remain intact).

**Comment by D-Brox** [comment]
> @D-Brox gives="i3lock i3lock-color" was already present in the script , is double quotes instead of the bracket creating the problem?

Yes, you need to use the parentheses so that pacstall treats it as a list.

> Also in the development branch the downloading of build files in not working, the hashcheck function is not able to find the file

Can you try running the new installer as wizard suggested.

**Comment by harsh18262** [comment]
Srry got a little busy with my examsi  will try it today and report back

**Comment by harsh18262** [comment]
I tried the new installer but got the same issue. I am attaching the screenshot
https://pasteboard.co/tqVJIhyLfeJY.png

There is some problem while downloading the file. it tries to restart the download but fails

I also tried another package but the same problem.
Screenshot:
https://pasteboard.co/GeMqWqwj4KaK.png
