### ISSUE TITLE
Install licenses along with the programs

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall-programs#36]
**Describe the bug**
Currently, most of the pacscripts don't install the license of the software that they are installing, this is actually illegal as you are basically coping the code without the license 

**To Reproduce**
NA.

**Expected behavior**
Obvious

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: NA
 - Version NA

**Additional context**
I am thinking of adding a message to the @pacstall/pacscript-maintainers to inform everyone about this.
#35  is a pacscript that installs the licenses, please follow similar commands to install the licenses.

**Comment by Henryws** [comment]
Where would the licenses go?

**Comment by Henryws** [comment]
I have a cool idea. There could be a directory somewhere, and pacscripts have an array of licenses, that correspond to a plain text url with the full license and downloads it

**Comment by D3SOX** [comment]
I will add the license stuff to my package like in my AUR package in a minute https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=soundux#n23
This should be fine.

**Comment by wizard-28** [comment]
Like I said #35 installs the licenses in `/usr/share/licenses/$name` just like the AUR.

**Comment by Henryws** [comment]
Sure, I still think the license array would be cool, and, users could specify what type of licensed software they want to download, like portage

**Comment by kaistian** [comment]
> Currently, most of the pacscripts don't install the license of the software that they are installing, this is actually illegal as you are basically coping the code without the license

I don't understand where this "illegal" comes from.
Pacstall do not distribute the code or binary, it's just a tool(a series of commands) to make the end user able to download the code to there machine, build, compile and install it them self.

With GPL-3 you don't even need to accept the license to run the program, it only apply when you "modifying or propagating a covered work" all this have it's own section in the license starting like this
> 9. Acceptance Not Required for Having Copies.
>
> You are not required to accept this License in order to receive or run a copy of the Program.

I have also look at the MIT and Apache license and I do not find a requirement to install a license.

**Comment by wizard-28** [comment]
> I don't understand where this "illegal" comes from.
Pacstall do not distribute the code or binary, it's just a tool(a series of commands) to make the end user able to download the code to there machine, build, compile and install it them self.

Technically, you are required to receive a copy of the GPL, when you receive/compile a binary. And since pacstall is compiling and building the source, **it is** distributing it to the user.

Here are some FAQs
![img](https://0x0.st/-LJ8.png)
![img2](https://0x0.st/-LJK.png)

Basically since we are installing free software we are required to install the license, so the users get to know their rights.

> Acceptance Not Required for Having Copies.
You are not required to accept this License in order to receive or run a copy of the Program.

It says **accept** not **recieve**. According to the GPL the user is supposed to receive a copy of it, along with the program itself.

![img](https://0x0.st/-LJP.png)
It says **You should have received a copy of the GNU General Public License along with Pacstall.** (or any other GPLed program).

**Comment by Leseratte10** [comment]
pacstall is just a program. It's a program that you can download and install onto your machine. Then, that program reads a config file where it sees how a given program can be downloaded (the pacscript file). 

The user is then actually the one downloading that. That's the same as if you would say, a bash script with the command `wget https://example.com/binary-thats-under-the-gpl` in it would be illegal because it does only load the binary, not the license. 

That's not the case. With that bash script, the operator of "example.com" is who is distributing the binary, and as long as the license is available on example.com, that's just fine. With pacstall, whoever operates the webserver behind the URL inside the pacscript is the one who is distributing the binary.

Yes, a package manager should install the program's license with the program. But it is not legally required to do that.

**Comment by wizard-28** [comment]
Thank you @Leseratte10 for you input! I am closing this issue then.
