### ISSUE TITLE
Unable to install makedeb-deb - 502 Bad Gateway

### ISSUE THREAD

**Issue by RDKRACZ** [pacstall/pacstall-programs#3965]
### Describe the bug

```
pacstall -I makedeb-deb
(makedeb-deb) Do you want to view/edit the pacscript [y/N] 
[+] INFO: Sourcing pacscript
[+] INFO: Retrieving packages
Initializing download: https://proget.hunterwittenborn.com/debian-feeds/makedeb/main/makedeb/all/makedeb_all_16.0.0-stable.deb
ERROR 502: Bad Gateway.
[!] ERROR: Failed to download package
[+] INFO: Cleaning up

```

### To reproduce

provided above

### Expected behavior

successful installation

### Screenshots

N/A

### OS version

Ubuntu 20.04 LTS

### Pacstall version

3.15.0 Rhythm

**Comment by RDKRACZ** [comment]
This did not fix the issue:
```
[+] INFO: Retrieving packages
Initializing download: https://proget.makedeb.org/debian-feeds/makedeb/main/makedeb/all/makedeb_all_16.0.0-stable.deb
ERROR 502: Bad Gateway.
[!] ERROR: Failed to download package
[+] INFO: Cleaning up
```

https://proget.makedeb.org/debian-feeds/makedeb/main/makedeb/all/makedeb_all_16.0.0-stable.deb

**Comment by Elsie19** [comment]
It seems that makedebs proget instance is down @hwittenborn

**Comment by hwittenborn** [comment]
There's some Cloudflare stuff installing on my server that's been causing memory leaks and keeps causing my server to crash. I'm going to be deploying a new program in about an hour, but the ProGet instance should already be back up.
