### ISSUE TITLE
Error installing a package

### ISSUE THREAD

**Issue by KarkanAlzwayed** [pacstall/pacstall-programs#408]
I don't know if this is because of the theme itself, and maybe it is not compatible with my DE (kde plasma), or if it is a pacstall issue, but when I tried installing cutefish-icons I am getting an error. Here is the terminal output:
 ```
pacstall -I cutefish-icons
Do you want to view/edit the pacscript [y/N] N
[+] INFO: Sourcing pacscript
[*] WARNING: Package does not contain a hash
[!] ERROR: Package does not contain version
```

I tried to install Brave browser, and it worked just fine.

**Comment by D-Brox** [comment]
We are (almost) always available on the discord server

**Comment by KarkanAlzwayed** [comment]
I'm still getting this error:
```
 pacstall -I cutefish-icons-git
Do you want to view/edit the pacscript [y/N] N
[+] INFO: Sourcing pacscript
[!] ERROR: Package does not contain version

```

**Comment by Henryws** [comment]
ah, the issue is that the master branch for them is called main, can you edit the script and replace `master` with `main`?

**Comment by KarkanAlzwayed** [comment]
Where is that located. I used the `.deb` package.

**Comment by Henryws** [comment]
Oh, no, I mean in the pacscript, when it asks you if you want to view it, accept, and change `master` to `main` in the script

**Comment by Henryws** [comment]
try now
