### ISSUE TITLE
Xapps

### ISSUE THREAD

**Issue by Elsie19** [pacstall/pacstall-programs#4173]
Hey @Zahrun!

https://github.com/pacstall/pacstall-programs/blob/master/packages/xapps-common-deb/xapps-common-deb.pacscript
https://github.com/pacstall/pacstall-programs/blob/master/packages/libxapp1-deb/libxapp1-deb.pacscript
https://github.com/pacstall/pacstall-programs/blob/master/packages/gir1.2-xapp-1.0-deb/gir1.2-xapp-1.0-deb.pacscript

These packages are all upstream and up to date in the debian sid + mantic repos, so are these still needed for any purpose?

**Comment by Zahrun** [comment]
They allow installing hypnotix-deb in bookworm, jammy, and lunar
