### ISSUE TITLE
PacReq: gitui

### ISSUE THREAD

**Issue by lebakasable** [pacstall/pacstall-programs#4206]
### Types

-bin (Binary release of the package), -git (Compiled off of the latest commit of the package)

### URL

https://github.com/extrawurst/gitui

### Building guide

https://github.com/extrawurst/gitui#7--build-top-

**Comment by pythoncrazy** [comment]
Hey there, I'm working on the -git version of the package currently, will be done in a hour or so

**Comment by pythoncrazy** [comment]
done, took little longer than I wanted.

**Comment by pythoncrazy** [comment]
Just for future reference, the pull request that implemented this was: https://github.com/pacstall/pacstall-programs/pull/6128
