### ISSUE TITLE
PacReq: Hyprland + Nvidia Patches

### ISSUE THREAD

**Issue by NichCrusie** [pacstall/pacstall-programs#4208]
### Types

-bin (Binary release of the package)

### URL

https://build.opensuse.org/package/show/openSUSE:Factory/hyprland

### Additional context

I know this on the OBS, but you can also build from source from the official repos, I think building off OBS would be great since this one includes the much needed Nvidia patches OOB. I would say SDDM would be a much needed dependency as well. 

If anyone can show me how to build this for Pacstall I am more than happy to maintain it!

**Comment by Elsie19** [comment]
I've tried to build Hyprland on Ubuntu before, even on Rhino Linux (devel repos), and it fails to install. I've tried downloading the tarballs for all the dependencies and it still fails, even with as bleeding edge as I could get all the deps. I don't think it's possible to do it right now.
