### ISSUE TITLE
`android-studio` is installing the preview release

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall-programs#4235]
`android-studio` is installing Android Studio Preview release Hedgehog (2023.1.1) Canary 10 whereas the stable release is 2022.3.1 (Giraffe)
Should there be two packages so that we can select the release we want, or should this package be renamed to 'android-studio-preview' or 'android-studio-canary'?

**Comment by oklopfer** [comment]
We are shipping whatever Repology considers the latest: https://repology.org/project/android-studio/versions
If anything, this should remain untouched, and we should instead additionally ship an `android-studio-stable`.

**Comment by oklopfer** [comment]
Done now https://github.com/pacstall/pacstall-programs/commit/63b7603f3228b58a7309e97564bdc9783d05e534

**Comment by Zahrun** [comment]
Thanks
