### ISSUE TITLE
PacReq: Android Studio

### ISSUE THREAD

**Issue by SamiYusuff** [pacstall/pacstall-programs#4431]
### URL

https://developer.android.com/studio

### Additional context

I want Android Studio to be added. The current Android Studio is the Android Studio Canary version. You can open a separate package for Canary called Android Studio Canary, but I think the actual version of Android Studio should be a separate package.

**Comment by oklopfer** [comment]
Done. https://github.com/pacstall/pacstall-programs/commit/63b7603f3228b58a7309e97564bdc9783d05e534
