### ISSUE TITLE
Package dupicated

### ISSUE THREAD

**Issue by Xdavius** [pacstall/pacstall-programs#4480]
Package Discord and discord-deb are identical.

Please consider removing one of both

Better using discord-deb for better naming.

regards,

davius

**Comment by oklopfer** [comment]
> Package Discord and discord-deb are identical.
> 
> Please consider removing one of both
> 
> Better using discord-deb for better naming.
> 
> regards,
> 
> davius

They are not the same. `discord` uses the source tarball. `discord-deb` uses a .deb file.
