### ISSUE TITLE
PacReq: <Lunacy>

### ISSUE THREAD

**Issue by Runa-Chin** [pacstall/pacstall-programs#4529]
### Types

-deb (Debian achieve release of the package)

### URL

https://lcdn.icons8.com/setup/Lunacy.deb

### Additional context

I just wanna make install Lunacy is simple by using Pacstall and not to need use Snap anymore for install that.

**Comment by spaceguybob** [comment]
This should be simple enough, I'll work on it after I get home from work later today unless someone else does it in the meantime

**Comment by spaceguybob** [comment]
https://github.com/pacstall/pacstall-programs/pull/4530

**Comment by Runa-Chin** [comment]
> This should be simple enough, I'll work on it after I get home from work later today unless someone else does it in the meantime

Thanks for response, i'll wait until they can be installed on Pacstall and make them easier to install and use. By the way, Lunacy was great software for every designer and they're free to use.

**Comment by spaceguybob** [comment]
Yes, it does appear I've come across a major issue though, they do not ship versioned download links, at least not where you linked me. This means that it can't really be shipped in pacatall very easily

**Comment by Runa-Chin** [comment]
> Yes, it does appear I've come across a major issue though, they do not ship versioned download links, at least not where you linked me. This means that it can't really be shipped in pacatall very easily

They're very close for about versioning and featuring, and really hard for getting known more about what's change from Lunacy until they announced officially to public what's new on Lunacy. I've seen the Flatpak version, and really too difficult for get known insidely about versioning and changelog.

**Comment by Runa-Chin** [comment]
> > Yes, it does appear I've come across a major issue though, they do not ship versioned download links, at least not where you linked me. This means that it can't really be shipped in pacatall very easily
> 
> They're very closed for about versioning and featuring, and really hard for getting known more about what's change from Lunacy until they announced officially to public what's new on Lunacy. I've seen the Flatpak version, and really too difficult for get known insidely about versioning and changelog.

But, after I'm finding again, I got versions information about Lunacy from official release notes. Here are URL about release notes from Icons8 for about versioning. I made my mistakes about in above discuss. 

Lunacy **(Official release notes)**
https://lunacy.docs.icons8.com/release-notes/

Sorry about my mistakes in above discussion.

**Comment by spaceguybob** [comment]
> > > Yes, it does appear I've come across a major issue though, they do not ship versioned download links, at least not where you linked me. This means that it can't really be shipped in pacatall very easily
> > 
> > They're very closed for about versioning and featuring, and really hard for getting known more about what's change from Lunacy until they announced officially to public what's new on Lunacy. I've seen the Flatpak version, and really too difficult for get known insidely about versioning and changelog.
> 
> But, after I'm finding again, I got versions information about Lunacy from official release notes. Here are URL about release notes from Icons8 for about versioning. I made my mistakes about in above discuss. 
> 
> Lunacy **(Official release notes)**
> https://lunacy.docs.icons8.com/release-notes/
> 
> Sorry about my mistakes in above discussion. 

The issue is not them releasing update notices, but them not releasing a versioned .deb that makes it near impossible to package

**Comment by Runa-Chin** [comment]
> > > > Yes, it does appear I've come across a major issue though, they do not ship versioned download links, at least not where you linked me. This means that it can't really be shipped in pacatall very easily
> > > 
> > > 
> > > They're very closed for about versioning and featuring, and really hard for getting known more about what's change from Lunacy until they announced officially to public what's new on Lunacy. I've seen the Flatpak version, and really too difficult for get known insidely about versioning and changelog.
> > 
> > 
> > But, after I'm finding again, I got versions information about Lunacy from official release notes. Here are URL about release notes from Icons8 for about versioning. I made my mistakes about in above discuss.
> > Lunacy **(Official release notes)**
> > https://lunacy.docs.icons8.com/release-notes/
> > Sorry about my mistakes in above discussion.
> 
> The issue is not them releasing update notices, but them not releasing a versioned .deb that makes it near impossible to package

Ah, I see. Maybe what I've sad in above is not release info, but they really closes about Debian packages and that makes imposibble to involve it on Pacstall. Thanks for response, next time I'll issuing a other software with FOSS access or involve my own programs to package it on Pacstall. I'll close this issue for now.
