### ISSUE TITLE
PacReq: VirtualBox

### ISSUE THREAD

**Issue by RandomnessRobin** [pacstall/pacstall-programs#4541]
### Types

-deb (Debian achieve release of the package)

### URL

https://download.virtualbox.org/virtualbox/7.0.10/virtualbox-7.0_7.0.10-158379~Ubuntu~jammy_amd64.deb

**Comment by Rockstar9604** [comment]
Hi @RandomnessRobin,
VirtualBox is now available with PR #4753 :)
