### ISSUE TITLE
PacReq: openrgb

### ISSUE THREAD

**Issue by iFanatical** [pacstall/pacstall-programs#4567]
### Types

nosuffix (Compiled off of the released source code)

### URL

https://aur.archlinux.org/packages/openrgb

### Building guide

https://gitlab.com/CalcProgrammer1/OpenRGB

**Comment by Xdavius** [comment]
Done #6253 

Will not provide versionned from source: useless

@Elsie19

**Comment by StefiaStefia** [comment]
> Done #6253 
> 
> Will not provide versionned from source: useless
>
