### ISSUE TITLE
PacReq: `SpaceCadetPinball-git`

### ISSUE THREAD

**Issue by echometerain** [pacstall/pacstall-programs#472]
Reverse engineering of 3D Pinball for Windows – Space Cadet, a game bundled with Windows.

URL: https://github.com/k4zmu2a/SpaceCadetPinball
Building Guide: https://github.com/k4zmu2a/SpaceCadetPinball/blob/master/README.md
Requested by me

**Comment by wizard-28** [comment]
What type of package do you request?

**Comment by echometerain** [comment]
A game

**Comment by echometerain** [comment]
yeah it's a -git
