### ISSUE TITLE
PacReq: <Ventoy>

### ISSUE THREAD

**Issue by anwaruddin2k** [pacstall/pacstall-programs#5052]
### Types

-bin (Binary release of the package)

### URL

https://sourceforge.net/projects/ventoy/files/v1.0.96

### Additional context

Ventoy is an open source tool to create bootable USB drive for ISO/WIM/IMG/VHD(x)/EFI files.

**Comment by Xdavius** [comment]
@Elsie19 Hi,
This package will be great. I don't know how to up a PacReq.

Regards.

Davius

**Comment by Elsie19** [comment]
> @Elsie19 Hi,
> This package will be great. I don't know how to up a PacReq.
> 
> Regards.
> 
> Davius

What do you mean "up a pacreq"?

**Comment by Xdavius** [comment]
> > @Elsie19 Hi,
> > This package will be great. I don't know how to up a PacReq.
> > Regards.
> > Davius
> 
> What do you mean "up a pacreq"?

I mean, setting it as required =) 

I will add it soon I think

**Comment by Xdavius** [comment]
duplicate here

https://github.com/pacstall/pacstall-programs/issues/2278
