### ISSUE TITLE
PacReq: `fzf-bin`

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall-programs#570]
URL: https://github.com/junegunn/fzf
Building Guide: https://github.com/junegunn/fzf/blob/master/README.md

There is an `install` script, which automatically installs `fzf`. Try to redirect where it installs stuff to `pkgdir`

**Comment by erenfro** [comment]
I went above and beyond on this one to include manpages, shell completions, documentations, etc from the same source, just using the pre-compiled binary that's usable in current Debian/Ubuntu  distros.
