### ISSUE TITLE
PacReq: `Bottles`

### ISSUE THREAD

**Issue by echometerain** [pacstall/pacstall-programs#576]
Basically playonlinux but better

URL: https://github.com/bottlesdevs/Bottles/tree/master
Building Guide: https://docs.usebottles.com/getting-started/installation (Other Packages > Build from source)

Requested By: @echometerain

**Comment by wizard-28** [comment]
AUR script: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bottles
