### ISSUE TITLE
PacReq: hyfetch

### ISSUE THREAD

**Issue by K0-RR** [pacstall/pacstall-programs#5924]
### Types

-bin (Binary release of the package), nosuffix (Compiled off of the released source code)

### URL

https://github.com/hykilpikonna/hyfetch/

### Building guide

It's python and shell

### Additional context

Now when neofetch is officially discontinued I think is a good time to revisit this. #4521, #4525

**Comment by pythoncrazy** [comment]
Almost done with this, just double checking

**Comment by pythoncrazy** [comment]
A pull request has been opened: https://github.com/pacstall/pacstall-programs/pull/6138
