### ISSUE TITLE
Pakage Outdated: `git-delta-deb`

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall-programs#616]
`git-delta-deb`'s latest release is `0.11.3`, while the pacscript is of `0.8.3`.

@kwon37xi update the pacscript, or just remove yourself as the maintainer if you no longer wish to maintain it. I could (or somebody else) could maintain the script then.

**Comment by kwon37xi** [comment]
I updated the version and removed myself from the maintainers.
