### ISSUE TITLE
Help: pacscript fails

### ISSUE THREAD

**Issue by paulcosma97** [pacstall/pacstall-programs#622]
**Describe the bug**
Probably not a bug but a mistake on my side. The installation process fails before even running `build` and possibly `prepare`.

**To Reproduce**
1. Try to install the following `pacscript`
```bash
name="nodejs"
pkgname="nodejs" # if this is a -git, -bin, etc. package, this would be the package name without extension
breaks="${pkgname} ${pkgname}-git ${pkgname}-bin ${pkgname}-app ${pkgname}-deb"
replace="${pkgname} node"
gives="${pkgname} node"
build_depends="python3 g++ make"
description="Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine."
maintainer="Paul Cosma <paul.cosma97@gmail.com>"

pkgver() {
 curl -Ls https://nodejs.org/en/download | grep -o "Latest LTS Version: <strong>.*</strong>" | grep -o --color=never "[1-9][0-9]*\.[0-9]*\.[0-9]*"
}

version="$(pkgver)"
url="https://github.com/nodejs/node/archive/v$version/nodejs-$version.tar.gz"

prepare() {
  true
}

build() {
  cd "node-$version"
  ./configure
  make -j"$(nproc)"
}

install() {
  sudo make install DESTDIR="${STOWDIR}/${name}"
}
```

**Expected behavior**
`build` function should be invoked

**Screenshots**
![image](https://user-images.githubusercontent.com/16655260/148468575-cfb90a34-c469-437f-991b-18083a63c89f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu minimal fresh install
 - Version 21.10

**Additional context**
I love the idea of AUR on Ubuntu so I'm trying to learn how to create packages. Please take my code with a grain of salt.

**Comment by Henryws** [comment]
`gives` can only have one variable on the inside

**Comment by paulcosma97** [comment]
In `make-a-pacscript.md` the following example is given: `gives="${pkgname} libfoo"`

**Comment by paulcosma97** [comment]
Anyway, that solved my issue. Thanks!

**Comment by Henryws** [comment]
Oops, that's outdated! Lemme do a PR really quick!
