### ISSUE TITLE
`install` not being invoked

### ISSUE THREAD

**Issue by paulcosma97** [pacstall/pacstall-programs#625]
**Describe the bug**
I created a `pacscript` and the `deb` installation works but `install` function is not invoked.

**To Reproduce**
1. Install this `pacscript`
```bash
name="nodejs-deb"
pkgname="nodejs"
breaks="${pkgname} ${pkgname}-git ${pkgname}-bin ${pkgname}-app ${pkgname}-deb"
replace="${pkgname} node"
gives="${pkgname}"
description="Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine."
maintainer="Paul Cosma <paul.cosma97@gmail.com>"
hash="f7336a4baa5556611f726267384edc3fdafb62a65ee7f03db5eae5b8ab01f91b"

pkgver() {
 curl -Ls https://nodejs.org/en/download | grep -o "Latest LTS Version: <strong>.*</strong>" | grep -o --color=never "[1-9][0-9]*\.[0-9]*\.[0-9]*"
}

version="$(pkgver)"
url="https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.13.1-deb-1nodesource1_amd64.deb"

prepare() {
  true
}

build() {
  true
}

install() {
  sudo mkdir -p "${STOWDIR}/${name}/usr/bin"
  sudo mkdir -p "${STOWDIR}/${name}/usr/include"
  sudo mkdir -p "${STOWDIR}/${name}/usr/share/man/man1"
  
  sudo mv /usr/bin/node "${STOWDIR}/${name}/usr/bin"
  sudo mv /usr/include/node "${STOWDIR}/${name}/usr/include"
  sudo mv /usr/share/man/man1/node.1.gz "${STOWDIR}/${name}/usr/share/man/man1"
  
  sudo ln -s "${STOWDIR}/${name}/usr/bin/node" /usr/bin/node  
  sudo ln -s "${STOWDIR}/${name}/usr/include/node" /usr/include/node  
  sudo ln -s "${STOWDIR}/${name}/usr/share/man/man1/node.1.gz" /usr/share/man/man1
}
```

**Expected behavior**
`install` should be invoked and all binaries should be moved to `STOWDIR` and symlinked.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Ubuntu minimal fresh install
 - Version 21.10

**Additional context**
I'm saying that `install` in not invoked because there are no directories in `STOWDIR` and no error prints.

**Comment by wizard-28** [comment]
Why are you trying to move those binaries to `${STOWDIR}`?

**Comment by paulcosma97** [comment]
I thought that I was supposed to do according to the docs
```bash
STOWDIR="/usr/src/pacstall" # Package install directory, symlinked at the end of install
```

**Comment by wizard-28** [comment]
> I thought that I was supposed to do according to the docs
> 
> ```shell
> STOWDIR="/usr/src/pacstall" # Package install directory, symlinked at the end of install
> ```

That's not required for `-deb` packages, neither is `pkgver` nor any of the functions (`prepare`, `build`, `install`). We should probably clear that up in the docs.

**Comment by Henryws** [comment]
Also don't symlink files to `/` manually, Pacstall will take care of that for you

**Comment by wizard-28** [comment]
Here's an example of a `-deb` script: https://github.com/pacstall/pacstall-programs/blob/c1377a8e93cd94ab551cdc40866f72fa5df69f14/packages/opera-beta-deb/opera-beta-deb.pacscript

**Comment by paulcosma97** [comment]
Ooh, that makes sense. I was also thinking of making the `pacscript` check for new versions. Would it be fine to have `version` and `url` computed ?

**Comment by wizard-28** [comment]
> Ooh, that makes sense. I was also thinking of making the `pacscript` check for new versions. Would it be fine to have `version` and `url` computed ?

How would you update the `hash` automatically that way?

**Comment by paulcosma97** [comment]
You're correct, I forgot about that. Thanks!

**Comment by paulcosma97** [comment]
@wizard-28 another question - do you have a discord or chat to ask for this kind of questions? I'm aware that posting questions as issues might not be the best idea

**Comment by Henryws** [comment]
Yes we do! https://discord.gg/thbY7nHp
