### ISSUE TITLE
PacReq: gamescope

### ISSUE THREAD

**Issue by RoyvanEmpel** [pacstall/pacstall-programs#6369]
### Types

-git (Compiled off of the latest commit of the package)

### URL

https://github.com/ValveSoftware/gamescope

### Building guide

https://github.com/ValveSoftware/gamescope/blob/master/README.md

### Additional context

The ubuntu / debian packages are out of date.

**Comment by oklopfer** [comment]
there is currently a WIP PR for this: https://github.com/pacstall/pacstall-programs/pull/6270

**Comment by RoyvanEmpel** [comment]
Alright, i am closing this one.
