### ISSUE TITLE
BugRep: `exa-git` requires extra dependency

### ISSUE THREAD

**Issue by saenai255** [pacstall/pacstall-programs#644]
**Describe the bug**
`exa-git` requires `rust` to be built

**To Reproduce**
1. Don't have `rust` installed
2. `pacstall -I exa-git`

**Expected behavior**
`rust` should be a build dependency

**Screenshots**
![image](https://user-images.githubusercontent.com/16655260/149035480-5dc464ff-9de7-48e1-8f9b-f9d4cf15b8ae.png)

**Desktop (please complete the following information):**
 - Pop!_OS
 - 21.10

**Additional context**
Nope

**Comment by wizard-28** [comment]
I don't maintain `exa-git`. Why am I assigned to this?

Assigning @Henryws
