### ISSUE TITLE
Outdated package: hyprland

### ISSUE THREAD

**Issue by K0-RR** [pacstall/pacstall-programs#6494]
The pacstall version is 0.35.0-1, from 05 Feb 2024.
`hyprland-bin` also lags behind for a few months now.

**Comment by Elsie19** [comment]
Hey, I'm the maintainer of the packages. `hyprland` probably won't get updates again. It was a very volatile package and requires many packages to be built from source.

As for `hyprland-bin`, I am aware. The only way I can proceed with updating it is if Ubuntu LTS bumps [libinput](https://packages.ubuntu.com/noble/libinput-bin) to 1.26. Until then, the binary cannot begin to work on Ubuntu.

**Comment by oklopfer** [comment]
I have vested interest in `hyprland` continuing maintenance as it is the only way for arm64 to use hyprland right now. It will absolutely get updates again, but as the label more accurately implies, this is *stalled* right now, until one of us can pick up on it again. Like Elsie said, there are a lot of new packages that constantly have to be added that are built from source.

**Comment by Elsie19** [comment]
We're updating hyprland-bin with the release of Ubuntu Oracular in #6526.
