### ISSUE TITLE
PacReq: Linux kernel LTS 6.6

### ISSUE THREAD

**Issue by jimed-rand** [pacstall/pacstall-programs#6586]
### Types

-deb (Debian packages)

### URL

https://kernel.ubuntu.com/mainline/v6.6.51/ (Sources)

### Building guide

I'll create 3 commits (2 dependencies and main package) and here's merge map below

`linux-longterm-6.6-modules-deb` --> `linux-longterm-6.6-headers-deb` --> `linux-longterm-6.6-deb`

After the end of merge map has been reached and all has been merged, Close the request as all commit had been merged.

### Additional context

The latest LTS kernel today are `6.6.58`, but only `6.6.51` avaliable on sources.

**Comment by jimed-rand** [comment]
To save time, for the `packagelist` file I will write it all at once as below.

``sh
linux-longterm-6.6-deb
linux-longterm-6.6-headers-deb
linux-longterm-6.6-modules-deb
```

I commit this section in the commit for `linux-longterm-6.6-modules-deb`, again to save time.

**Comment by jimed-rand** [comment]
So, for commit `linux-longterm-6.6-headers-deb` and `linux-longterm-6.6-deb`, merge it immediately after merging `linux-longterm-6.6-modules-deb`.

**Comment by jimed-rand** [comment]
Something's wrong, I'll convert #6611 and #6612 into draft. So don't touch the commit unless it's ready to commit

**Comment by jimed-rand** [comment]
Commit #6611 ready to review. And also, #6612 will keep being drafted until #6611 has been merged.

**Comment by jimed-rand** [comment]
Alright, new plan. After `linux-longterm-6.6-modules-deb` has been merged, I revise the merge map for the `headers` section. Here's the merge map below.

`linux-longterm-6.6-headers-modular-deb` -> `linux-longterm-6.6-headers-deb` -> `linux-longterm-6.6-deb`

For this (`linux-longterm-6.6-headers-modular-deb`), it's actually kernel headers with `all` flags because it supports both `amd64` and `arm64`, so for the `arch` flag are `all` instead `any`. So, follow this merge map and after `linux-longterm-6.6-deb` has been merged, you can close this requests issues as completed.

**Comment by jimed-rand** [comment]
#6612 closed as unplanned because I got missing dependencies. After looking what's missing, I guess it could need new merge map.

**Comment by oklopfer** [comment]
Completed in https://github.com/pacstall/pacstall-programs/commit/d7d1724430723e8436cf0b2e06b6ab0b46267545
