### ISSUE TITLE
PacReq: LegCord

### ISSUE THREAD

**Issue by siren15** [pacstall/pacstall-programs#6616]
### Types

-deb (Debian achieve release of the package)

### URL

(deb) https://github.com/Legcord/Legcord/releases/download/v1.0.2/Legcord-1.0.2-linux-amd64.deb
(repo) https://github.com/Legcord/Legcord

### Building guide

https://github.com/Legcord/Legcord?tab=readme-ov-file#compiling

### Additional context

ArmCord, the alternative discord client, is rebranding to LegCord, due to ARM sending them cease and desist letter. And are currently not providing legcord in the main repos yet.

**Comment by jimed-rand** [comment]
Thanks for your request, I'll create the commit for this as `legcord-deb`

**Comment by siren15** [comment]
closing this, seeing as this was basically done in https://github.com/pacstall/pacstall-programs/pull/6642
Thanks ya'll.
