### ISSUE TITLE
GNU Nano fails to install

### ISSUE THREAD

**Issue by cat-master21** [pacstall/pacstall-programs#671]
**Describe the bug**
Nano Installs an additional APT package which do not exist. This package 'auto' is not in PKGBUILD oddly also.

**To Reproduce**
1. Install Pacstall
2. Install Nano by: `pacstall -I nano`
3. Notice that installation fails because of trying to install package auto which does not exist.

**Expected behavior**
Nano fails to install because of nonexistent package.

**Screenshots**
![Screenshot from 2022-01-25 19-44-17](https://user-images.githubusercontent.com/96554164/151100856-cc8f874e-7093-48ee-a1ad-97d6d7a4c874.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04.3 LTS

**Comment by wizard-28** [comment]
I can't reproduce this on my Pop!_OS machine, it only asks to install `groff` & `texinfo` here.
![failed_reproduction_image](https://user-images.githubusercontent.com/49679481/151111815-fd6e3ed8-c0f2-401d-8cf5-da710393ef87.png)

@Henryws, can you test this in a docker container of Ubuntu 20.04 LTS.

**Comment by cat-master21** [comment]
Tried this on Debian Sid in a VM and it to had this issue: 
![Screenshot](https://user-images.githubusercontent.com/96554164/151257447-3b111288-eaba-4841-b4cc-6d0e77a9a791.png)

**Comment by Henryws** [comment]
Can you view the pacscript during install?

**Comment by cat-master21** [comment]
Here's what nano's PKGBUILD looks like from vim tiny:
![Screenshot from 2022-01-26 15-38-23](https://user-images.githubusercontent.com/96554164/151265446-63763550-8f9e-4610-9f99-22873b0d5f68.png)
And as you can see auto is not in the depends either oddly.

**Comment by Henryws** [comment]
I'm unable to produce this. Hmm

**Comment by D-Brox** [comment]
![image](https://user-images.githubusercontent.com/65723952/151272802-4d75deb2-db40-4514-8b99-ff2f8cb16522.png)
It's this substititution's fault

**Comment by Henryws** [comment]
Why is this an issue on @cat-master21's machine but no one elses?

**Comment by D-Brox** [comment]
`automake` is not installed but `make` is

**Comment by Henryws** [comment]
Welp, schedule it for 2.0.0

**Comment by D-Brox** [comment]
There is an easy fix tho

**Comment by D-Brox** [comment]
This behavior will not be present in v2.0

**Comment by cat-master21** [comment]
Yes, manually installing Automake fixed this issue fortunately for me.
