### ISSUE TITLE
Update Quarto to v1.6.39 in Pacstall Script

### ISSUE THREAD

**Issue by kulasegaram** [pacstall/pacstall-programs#6716]
https://github.com/pacstall/pacstall-programs/blob/3f7352189df9172752e90b7c34a2c78aacefa2ff/packages/quarto-deb/quarto-deb.pacscript#L3

Hello Pacstall team,

I hope this message finds you well! I wanted to bring to your attention that Quarto has recently released a new version, v1.6.39. However, this update has not yet been reflected in the Pacstall script.

Please update the Pacstall script to include this latest version. This will ensure that users can access the most recent features and improvements offered by Quarto.

Thank you for your hard work and dedication to maintaining Pacstall!

See: https://github.com/quarto-dev/quarto-cli/releases/tag/v1.6.39

**Comment by jimed-rand** [comment]
Anyway, I have already committed your request. So, you can close your request as complete
