### ISSUE TITLE
Update GitHub-Desktop to 3.4.8 in Pacstall Script

### ISSUE THREAD

**Issue by kulasegaram** [pacstall/pacstall-programs#6718]
https://github.com/pacstall/pacstall-programs/blob/3f7352189df9172752e90b7c34a2c78aacefa2ff/packages/github-desktop-deb/github-desktop-deb.pacscript#L3

Hello Pacstall team,

I hope this message finds you well! I wanted to bring to your attention that GitHub-Desktop has recently released a new version, 3.4.8. However, this update has not yet been reflected in the Pacstall script.

Please update the Pacstall script to include this latest version. This will ensure that users can access the most recent features and improvements offered by GitHub-Desktop.

Thank you for your hard work and dedication to maintaining Pacstall!

See: https://github.com/shiftkey/desktop/releases/tag/release-3.4.8-linux1

**Comment by jimed-rand** [comment]
Got it, @kulasegaram. I have your update requests working on it on #6726
