### ISSUE TITLE
PacReq: WebStorm, Rider, and RustRover

### ISSUE THREAD

**Issue by jimed-rand** [pacstall/pacstall-programs#6744]
### Types

-bin (Binary release of the package)

### URL

WebStorm : [Lists of versions and sources](https://www.jetbrains.com/webstorm/download/other.html)
Rider : [Lists of versions and sources](https://www.jetbrains.com/rider/download/other.html)
RustRover : [Main download pages](https://www.jetbrains.com/rust/download/?section=linux)

### Building guide

Same as IDEA and PyCharm which existing on Pacstall repo.

### Additional context

For this request, leave it to me.

**Comment by jimed-rand** [comment]
For WebStorm, I called `webstorm-bin` and now in process for adding into repo. Also, for Rider it will be called as `rider-bin` and for RustRover, i'll called it as `rustrover-bin`. After `webstorm-bin` had been merged, I'll continuing the commit for `rider-bin` then `rustrover-bin`.

**Comment by jimed-rand** [comment]
Rider and RustRover hasn't be added. So, I'll use this closed issue for refrences

**Comment by Elsie19** [comment]
For future reference, you should only make one of these per package.
