### ISSUE TITLE
PacReq: nerd-fonts-hack

### ISSUE THREAD

**Issue by ghost** [pacstall/pacstall-programs#806]
Patched font Hack from nerd-fonts library.

URL: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nerd-fonts-hack
Building Guide: https://gist.github.com/smac89/35d1c7576889419854e3c7d2684cb759
Error I get when trying: https://gist.github.com/HarleyQuinn-Z6/c521e9f2d585c0bcca1098a34f196779

`nerd-fonts-hack.pacscript`
```
name=nerd-fonts-hack
pkgname=nerd-fonts-hack
version="2.1.0"
url="https://github.com/ryanoasis/nerd-fonts/releases/download/v$version/Hack.zip"
description="Patched font Hack from nerd-fonts library"
hash="70852e59fcffbe31d401f615625bcb9ebb6af72732c2f1fe9b9d5370c2565514"
maintainer="ajr <public-dexd7c@ajr.anonaddy.com>"

prepare() {
    true
}

build() {
    true
}

install() {
    sudo install -d "$STOWDIR/$name"/usr/share/fonts/TTF
    rm "${SRCDIR}/"*"Windows Compatible.ttf"
    sudo install -Dm644 "${SRCDIR}/"*.ttf "$STOWDIR/$name"/usr/share/fonts/TTF
}
```

**Comment by Henryws** [comment]
Your `$name` is `nerd-fonts-hack-git` but your not pulling from a git repo 🤔

**Comment by HarleyQuinn-Z6** [comment]
Fixed that.

**Comment by Henryws** [comment]
Add
```bash
build() {
	true
}
```

**Comment by HarleyQuinn-Z6** [comment]
`Segmentation fault (core dumped)`

**Comment by Henryws** [comment]
Can you send the full log?

**Comment by wizard-28** [comment]
> Patched font Hack from nerd-fonts library.
> 
> URL: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nerd-fonts-hack
> Building Guide: https://gist.github.com/smac89/35d1c7576889419854e3c7d2684cb759
> Error I get when trying: https://gist.github.com/HarleyQuinn-Z6/c521e9f2d585c0bcca1098a34f196779
> 
> `nerd-fonts-hack.pacscript`
> ```
> name=nerd-fonts-hack
> pkgname=nerd-fonts-hack
> version="2.1.0"
> url="https://github.com/ryanoasis/nerd-fonts/releases/download/v$version/Hack.zip"
> description="Patched font Hack from nerd-fonts library"
> hash="70852e59fcffbe31d401f615625bcb9ebb6af72732c2f1fe9b9d5370c2565514"
> maintainer="ajr <public-dexd7c@ajr.anonaddy.com>"
> 
> prepare() {
>     true
> }
> 
> build() {
>     true
> }
> 
> install() {
>     install -d "$STOWDIR/$name"/usr/share/fonts/TTF
>     rm "${SRCDIR}/"*"Windows Compatible.ttf"
>     install -Dm644 "${SRCDIR}/"*.ttf "$STOWDIR/$name"/usr/share/fonts/TTF
> }
> ```

Your `install` commands in `install()` need `sudo`

**Comment by HarleyQuinn-Z6** [comment]
Nice. It's working now. You can add it to the packages. I don't use github since they stopped allowing user and password.
