### ISSUE TITLE
ERROR: Could not properly build neovim

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [pacstall/pacstall-programs#807]
**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04.4

I installed neovim with `sudo apt install neovim` and then removed it and tried to install it with pacstall:
https://pastebin.com/frJyhH7j

**Comment by Henryws** [comment]
Can you run:
```bash
ls /home/user/.config/dotfiles/install
```

**Comment by HarleyQuinn-Z6** [comment]
I did `sudo apt remove neovim` but I had to remove the runtime too, so `sudo apt remove neovim neovim-runtime`.
