### ISSUE TITLE
`steam-deb` uses 32bit deb

### ISSUE THREAD

**Issue by saenai255** [pacstall/pacstall-programs#838]
**Describe the bug**
Package `steam-deb` uses arch `i386` (`86x32`)

**To Reproduce**
`pacstall -I steam-deb`

**Expected behavior**
Should also have `x64` arch as it is the most used one

**Screenshots**
![image](https://user-images.githubusercontent.com/16655260/158018497-3b5eee3b-d5ed-4ad3-95ab-5cb8400a6b8e.png)

**Desktop (please complete the following information):**
 - OS: Debian
 - Bullseye `11`

**Comment by wizard-28** [comment]
@WRM-42 add `sudo dpkg --add-architecture i386` to the pacscript's body

https://github.com/pacstall/pacstall-programs/blob/0b5ef6d3e39ee32e551674aea7bf5ea763288778/packages/steam-deb/steam-deb.pacscript#L1

Probably before this line, we'll add a `preinstall` function in the next major release, where we can move this stuff, but for now it needs to be outside all functions.
