### ISSUE TITLE
PacReq: reshade-shaders-git

### ISSUE THREAD

**Issue by Mar0xy** [pacstall/pacstall-programs#901]
Package Type: git

I decided to open this mainly due to the conversation from #900 about the package not being in pacstall yet.

[PKGBUILD from AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=reshade-shaders-git)

**Comment by wizard-28** [comment]
I can make the script tomorrow.

**Comment by Mar0xy** [comment]
Alright :smiley:
